# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.15.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Helm charts template ⛵
reponame: template-helm
repourl: https://github.com/radio-aktywne/template-helm
templatename: helm
type: generic
